CREATE TABLE user_roles(
  role VARCHAR(16)  NOT NULL PRIMARY KEY
);
INSERT INTO user_roles VALUES ('GUEST');
INSERT INTO user_roles VALUES ('USER');
INSERT INTO user_roles VALUES ('AGENT');
INSERT INTO user_roles VALUES ('ADMIN');
